language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
env:
  -
  - SOLIDITY_COVERAGE=true
  - SOLC_NIGHTLY=true
jobs:
  include:
    - stage: build
      node_js: "8"
      script:
      - npm run test
      - npm run coverage
      - npm run coveralls
