version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - save_cache:
          - key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
