version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: v1-node-module
	  paths:
	    - ./node_modules
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
