version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-module

      - run: npm install
      - save_cache:
          key: v1-node-module
          paths:
            - ./node_modules
      - run: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
